#!/usr/bin/python


import os


#os.path.basename(os.getcwd())
name = "root"
print ""
print "uploading dump for", name
password = "root"
db = os.path.basename(os.getcwd())



def get_files(path):
    files = filter(lambda x: x.endswith('.sql') or x.endswith('.py'), os.listdir(path))
    return list(list((x, path+'/'+x) for x in files ))


all_files = []
all_files += get_files('../.deltas/dev')
all_files += get_files('../.deltas/done')

all_files += get_files('./deltas/done')
all_files += get_files('./deltas/pending')
all_files += get_files('./deltas/dev')
all_files += get_files('./deltas/fix')

all_files.sort()

uploaded = set()
for filename, path in all_files:
    if not filename in uploaded:
        if filename.endswith('.py'):
            print "projecting", filename
            os.system('python '+path+' >'+path+'.sql')
            os.system('mysql -u {0} -p{1} {2} <{3}'.format(name, password, db, path+".sql"))
        elif filename.endswith('.py.sql'):
            pass
        else:
            print "applying", path
            os.system('mysql -u {0} -p{1} {2} <{3}'.format(name, password, db, path))
        uploaded.add(filename)


